import { useState } from "react";
import { Loader2, UserRoundPlus, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { queueOperation } from "@/lib/offline";
import { trpc } from "@/lib/trpc";

const format = (value: number, currency: string) => new Intl.NumberFormat("fr-FR", { style: "currency", currency, maximumFractionDigits: 0 }).format(value || 0);

export default function CreditPanel({ shopId, currency }: { shopId: string; currency: string }) {
  const utils = trpc.useUtils(); const receivables = trpc.commerce.receivables.list.useQuery({ shopId, includeSettled: false }); const customers = trpc.catalog.customers.list.useQuery({ shopId });
  const [name, setName] = useState(""); const [repayments, setRepayments] = useState<Record<string, string>>({});
  const create = trpc.catalog.customers.create.useMutation({ onSuccess: () => { setName(""); utils.catalog.customers.list.invalidate({ shopId }); } }); const repay = trpc.commerce.receivables.repay.useMutation({ onSuccess: () => { utils.commerce.receivables.list.invalidate({ shopId }); utils.insights.dashboard.invalidate({ shopId }); } });
  const recordRepayment = async (receivableId: string, balance: number) => { const amount = Number(repayments[receivableId]); if (!amount || amount <= 0 || amount > balance) return; const payload = { shopId, receivableId, amount, operationId: crypto.randomUUID(), paymentMethod: "cash" as const }; if (!navigator.onLine) { await queueOperation("repayment", payload); setRepayments((values) => ({ ...values, [receivableId]: "" })); return; } repay.mutate(payload, { onSuccess: () => setRepayments((values) => ({ ...values, [receivableId]: "" })) }); };
  return <div className="grid gap-6 xl:grid-cols-[340px_1fr]"><Card className="h-fit border-0 bg-[#fdf0dc]"><CardContent className="p-4 sm:p-6"><div className="flex items-center gap-2"><UserRoundPlus className="h-5 w-5 text-[#9d632d]" /><p className="font-serif text-xl">Nouveau client</p></div><p className="mt-2 text-sm text-[#7f7464]">Créez un client avant de lui accorder un crédit à la caisse.</p><form onSubmit={(event) => { event.preventDefault(); create.mutate({ shopId, name }); }} className="mt-5 space-y-3"><label className="grid gap-2"><Label>Nom du client</Label><Input value={name} onChange={(event) => setName(event.target.value)} required /></label><Button disabled={!name || create.isPending} className="w-full bg-[#9d632d] hover:bg-[#82501f]" type="submit">{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Ajouter le client</Button></form><div className="mt-7 border-t border-[#eddabf] pt-5"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#8d7355]">Clients enregistrés</p><div className="mt-3 space-y-2">{customers.data?.slice(0, 6).map((customer) => <p key={customer.id} className="break-words text-sm">{customer.name}</p>)}</div></div></CardContent></Card><Card className="border-0 bg-white shadow-[0_12px_30px_rgba(43,47,38,0.05)]"><CardContent className="p-4 sm:p-7"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-[#a96551]" /><div><p className="font-serif text-xl">Créances en cours</p><p className="mt-1 text-xs text-[#85877f]">Enregistrez un remboursement complet ou partiel.</p></div></div><div className="mt-5 space-y-3">{receivables.data?.map(({ receivable, customerName }) => <article key={receivable.id} className="rounded-2xl border border-[#ece9df] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><p className="break-words font-semibold">{customerName}</p><p className="mt-1 text-xs text-[#85877f]">Solde initial : {format(receivable.originalAmount, currency)}</p></div><p className="font-semibold text-[#b05d4c]">{format(receivable.balance, currency)}</p></div><div className="mt-4 grid gap-2 sm:flex sm:items-center sm:justify-end"><Input type="number" min="1" max={receivable.balance} value={repayments[receivable.id] ?? ""} onChange={(event) => setRepayments((values) => ({ ...values, [receivable.id]: event.target.value }))} placeholder="Montant à encaisser" className="w-full sm:w-32" /><Button className="w-full sm:w-auto" disabled={repay.isPending || !repayments[receivable.id]} onClick={() => recordRepayment(receivable.id, receivable.balance)}>Encaisser</Button></div></article>)}{!receivables.data?.length && <p className="py-12 text-center text-sm text-[#85877f]">Aucune créance ouverte.</p>}</div></CardContent></Card></div>;
}
